version: 1.5.{build}
branches:
  only:
    - master
    - appveyor
skip_branch_with_pr: true
os: Visual Studio 2017
build_script:
  - ps: 'dotnet pack -c Release -o "$(pwd)/artifacts/" "-p:Version=${env:APPVEYOR_BUILD_VERSION}"'
test: off
artifacts:
  - path: '**\*.nupkg'
    name: Packages
    type: NuGetPackages
deploy:
  - provider: NuGet
    api_key:
      secure: 'Ct/FzRmVW44GcMstu2xsuGj05FqNBR2+b4CjjEgBfxCscUhi5UdnlnSSBjYVgjgn'
    skip_symbols: false
    artifact: Packages
    on:
      branch: master
      appveyor_repo_tag: true
  - provider: GitHub
    description: 'https://github.com/VictorioBerra/TemplateVersions.Tool'
    auth_token:
      secure: 'eYbKSKRTUpYFx1+8DzRYnROrYB4VJuYBBKSb7sFsqO3wOBi2jrJ88ioxrLpHDqI3'
    artifact: Packages
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true