version: 3.0.{build}
branches:
  only:
    - master
    - appveyor
skip_branch_with_pr: true
os: Visual Studio 2017
build_script:
  - ps: 'dotnet pack -c Release -o "$(pwd)/artifacts/" "-p:Version=${env:appveyor_build_version}"'
test: off
artifacts:
  - path: '**\*.nupkg'
    name: Packages
    type: NuGetPackages
deploy:
  - provider: GitHub
    tag: v$(appveyor_build_version)
    description: 'https://github.com/VictorioBerra/TemplateVersions.Tool'
    auth_token:
      secure: eYbKSKRTUpYFx1+8DzRYnROrYB4VJuYBBKSb7sFsqO3wOBi2jrJ88ioxrLpHDqI3
    artifact: Packages
    draft: true
    prerelease: false
    on:
      branch: master